### ISSUE TITLE
where is the blstm.model

### ISSUE THREAD

**Issue by ericosmic** [Xiao-Ming/ChordRecognitionMIDITrainedExtractor#1]
This source loss blstm.model, when run Estimate_Chords_From_Audio.py  , it will give a error info.

**Comment by Xiao-Ming** [comment]
Hi, 
thank you for commenting and apologies for late response!
The model should not have to load "blstm.model" at the estimation phase since crf_blstm.model includes the whole parameters, so I have omitted the code which executes unexpected loading process. Please see the latest commit. 
I'll include the blstm.model file in the repository anyway.
